export const pqgCopy = {
  brand: 'PQG',
  workspace: 'Không gian làm việc',
  home: 'Trang chủ',
  approval: 'Phê duyệt',
  modules: 'Ứng dụng',
  personal: 'Cá nhân',
  quickNote: 'Ghi chú nhanh',
  recent: 'Gần đây',
  favorites: 'Mục yêu thích',
  search: 'Tìm kiếm',
  searchPlaceholder: 'Tìm trong các ứng dụng...',
  searchHint: 'Nhập từ khóa để tìm kiếm.',
  searchLoading: 'Đang tìm...',
  searchEmpty: 'Không tìm thấy kết quả phù hợp.',
  support: 'Hỗ trợ',
  supportTitle: 'Trợ lý hỗ trợ',
  supportDescription: 'Ngữ cảnh và gợi ý cho khu vực bạn đang làm việc.',
  supportSuggestions: 'Gợi ý',
  supportCompact: 'Thu gọn',
  supportExpand: 'Mở rộng',
  supportClose: 'Đóng',
  homeTitle: 'Trang chủ',
  homeDescription: 'Mở nhanh công việc và tiện ích của bạn từ một nơi.',
  homeEmpty: 'Các tiện ích được mô-đun đóng góp sẽ xuất hiện tại đây.',
  approvalEmpty: 'Hiện không có hành động nào đang chờ bạn phê duyệt.',
  approvalAction: 'Hành động',
  approvalReason: 'Lý do',
  approvalReasonFallback: 'Hệ thống yêu cầu xác nhận trước khi tiếp tục.',
  approvalRisk: 'Mức xác nhận',
  approvalRiskConfirmation: 'Cần xác nhận',
  approvalAllow: 'Cho phép một lần',
  approvalReject: 'Từ chối',
  approvalAllowedNotification: 'Đã cho phép hành động một lần.',
  approvalRejectedNotification: 'Đã từ chối hành động.',
  approvalErrorNotification: 'Không thể gửi quyết định phê duyệt.',
  moduleUnavailable: 'Mô-đun hiện không khả dụng.',
  utilityUnavailable: 'Tiện ích này chưa được kích hoạt.',
} as const
