export const pqgCopy = {
  brand: 'PQG',
  workspace: 'Không gian làm việc',
  home: 'Trang chủ',
  approval: 'Phê duyệt',
  modules: 'Ứng dụng',
  personal: 'Cá nhân',
  quickNote: 'Ghi chú nhanh',
  recent: 'Gần đây',
  favorites: 'Mục yêu thích',
  support: 'Hỗ trợ',
  supportTitle: 'Trợ lý hỗ trợ',
  supportDescription: 'Ngữ cảnh và gợi ý cho khu vực bạn đang làm việc.',
  supportCompact: 'Thu gọn',
  supportExpand: 'Mở rộng',
  supportClose: 'Đóng',
  homeTitle: 'Trang chủ',
  homeDescription: 'Mở nhanh công việc và tiện ích của bạn từ một nơi.',
  homeEmpty: 'Các tiện ích được mô-đun đóng góp sẽ xuất hiện tại đây.',
  approvalUnavailable: 'Khu vực phê duyệt sẽ được kết nối ở giai đoạn triển khai riêng.',
  moduleUnavailable: 'Mô-đun hiện không khả dụng.',
  utilityUnavailable: 'Tiện ích này chưa được kích hoạt.',
} as const
