export const pqgCopy = {
  brand: 'PQG Harness',
  workspace: 'Không gian làm việc',
  home: 'Trang chủ',
  approval: 'Phê duyệt',
  modules: 'Ứng dụng',
  search: 'Tìm kiếm',
  searchPlaceholder: 'Tìm kiếm công việc, tài liệu, lịch họp...',
  searchHint: 'Nhập từ khóa để tìm kiếm.',
  searchLoading: 'Đang tìm...',
  searchEmpty: 'Không tìm thấy kết quả phù hợp.',
  support: 'Hỗ trợ',
  supportTitle: 'Trợ lý hỗ trợ',
  supportDescription: 'Luôn đồng hành cùng bạn trong công việc hằng ngày.',
  supportSuggestions: 'Gợi ý cho bạn',
  supportCompact: 'Thu gọn',
  supportExpand: 'Mở rộng',
  supportClose: 'Đóng',
  supportEmpty: 'Hãy đặt câu hỏi hoặc chọn một gợi ý để bắt đầu.',
  supportPlaceholder: 'Nhập yêu cầu của bạn…',
  supportSend: 'Gửi',
  supportStop: 'Dừng',
  supportWorking: 'Đang xử lý yêu cầu…',
  supportSendError: 'Không thể gửi yêu cầu cho Trợ lý.',
  supportStopError: 'Không thể dừng yêu cầu đang xử lý.',
  homeTitle: 'Bảng điều khiển',
  homeDescription: 'Chào mừng bạn trở lại! Cùng PQG Harness hoàn thành công việc hiệu quả hơn mỗi ngày.',
  dashboardWorkspaceTitle: 'Không gian làm việc hôm nay',
  dashboardWorkspaceDescription: 'Tất cả những gì bạn cần cho một ngày làm việc hiệu quả.',
  dashboardSessions: 'Phiên làm việc',
  dashboardCurrentSession: 'Phiên hiện tại',
  dashboardApproval: 'Cần phê duyệt',
  dashboardOpen: 'Đang mở',
  dashboardClosed: 'Chưa mở',
  homeEmpty: 'Các tiện ích được mô-đun đóng góp sẽ xuất hiện tại đây.',
  approvalEmpty: 'Hiện không có hành động nào đang chờ bạn phê duyệt.',
  approvalAction: 'Hành động',
  approvalReason: 'Lý do',
  approvalReasonFallback: 'Hệ thống yêu cầu xác nhận trước khi tiếp tục.',
  approvalRisk: 'Mức xác nhận',
  approvalRiskConfirmation: 'Cần xác nhận',
  approvalAllow: 'Cho phép một lần',
  approvalReject: 'Từ chối',
  approvalAllowedNotification: 'Đã cho phép hành động một lần.',
  approvalRejectedNotification: 'Đã từ chối hành động.',
  approvalErrorNotification: 'Không thể gửi quyết định phê duyệt.',
  moduleUnavailable: 'Mô-đun hiện không khả dụng.',
} as const
